POST http://127.0.0.1:8000/api/login HTTP/1.1
content-type: application/json

{
    "email": "teste1@email.com",
    "password": "q1w2e3r4"
}

###
GET http://127.0.0.1:8000/api/user HTTP/1.1
Authorization: Bearer 4|wz4tt98jtmMp2QFByTr9KU0kCBHBTHWfkT3oXBKD
